name: cloud_firestore_odm_generator_integration_test
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  cloud_firestore_odm:
    git:
      url: https://github.com/Flutter-Fox/firestoreodm-flutter.git
      ref: refactor/odm-2.0.0-dev.0
      path: packages/cloud_firestore_odm/
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: "4.9.0"

dev_dependencies:
  build_runner: "2.10.1"
  cloud_firestore_odm_generator:
    path: ../
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: "6.11.2"

dependency_overrides:
  analyzer: ^8.0.0
  cloud_firestore_odm:
    path: ../../cloud_firestore_odm

flutter:
  uses-material-design: false
